name: "Build"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix profile install nixpkgs#devenv
      - name: Build
        run: devenv shell -- pnpm build
      # Check that build was committed
      - name: Verify latest build
        run: git diff --exit-code

  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
    secrets: inherit
